import os
import sys
import pandas as pd

configfile: "config/config.yaml"

include: "rules/common.smk"
include: "rules/pb_germline.smk"
include: "rules/read_qc.smk"

samples = parse_sample_sheet(config)
reference = config["reference"]

rule all:
    input:
        parabricks_output
